### ISSUE TITLE
jQuery TS definitions file doesn't include jqLite version of .on()

### ISSUE THREAD

**Issue by bvaughn** [seanhess/angularjs-typescript#2]
The [jquery.d.ts](https://github.com/seanhess/angularjs-typescript/blob/master/public/js/types/jquery/jquery.d.ts) definition of `.on()` should include a version without the optional `selector` parameter since specifying that parameter will result in [a jqlite runtime error](https://docs.angularjs.org/error/jqLite/onargs):

```
jqLite#on() does not support the `selector` or `eventData` parameters
```

And TypeScript won't compile a jqLite-compatible version of the `.on()` method with the current definition:

```
error TS2345: Argument of type 'string' is not assignable to parameter of type '{ [key: string]: any; }'.
```

**Comment by seanhess** [comment]
Hi @bvaughn! 

I'm sorry to have confused you. I didn't intend for the definition files to be used from my repository. I'm just demonstrating where to put them. 

You should download the latest version from [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped). I bet their [jquery.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts) file already has your fix. 

They have TONS of different library definitions. Go check it out!

**Comment by seanhess** [comment]
Oh, and if it doesn't have your change, please issue a PR to DefinitelyTyped instead of here so everyone can benefit!

**Comment by bvaughn** [comment]
Haha, well that's funny. Thanks for responding so quickly. :)

Indeed you're right. They've already got the necessary definition. Much appreciated!
